import type { SettingsSectionDef } from "./registry";

export const SETTINGS_REGISTRY: readonly SettingsSectionDef[] = [
  {
    id: "general",
    titleKey: "settings.sections.general",
    items: [
      {
        id: "language",
        type: "select",
        titleKey: "settings.language.label",
        descriptionKey: "settings.language.description",
        options: [
          { value: "en", labelKey: "settings.language.options.en" },
          { value: "es", labelKey: "settings.language.options.es" },
        ],
        keywords: ["locale", "idioma", "lang"],
      },
      {
        id: "theme",
        type: "select",
        titleKey: "settings.theme.label",
        descriptionKey: "settings.theme.description",
        options: [
          { value: "dark", labelKey: "settings.theme.options.dark" },
          { value: "light", labelKey: "settings.theme.options.light" },
        ],
        keywords: ["dark", "light", "color", "color scheme", "tema"],
      },
      {
        id: "textScale",
        type: "select",
        titleKey: "settings.textScale.label",
        descriptionKey: "settings.textScale.description",
        options: [
          { value: "0.5", labelKey: "settings.textScale.options.50" },
          { value: "0.6", labelKey: "settings.textScale.options.60" },
          { value: "0.7", labelKey: "settings.textScale.options.70" },
          { value: "0.8", labelKey: "settings.textScale.options.80" },
          { value: "0.875", labelKey: "settings.textScale.options.87" },
          { value: "0.92", labelKey: "settings.textScale.options.92" },
          { value: "1", labelKey: "settings.textScale.options.100" },
          { value: "1.125", labelKey: "settings.textScale.options.112" },
          { value: "1.25", labelKey: "settings.textScale.options.125" },
          { value: "1.4", labelKey: "settings.textScale.options.140" },
        ],
        keywords: ["size", "font", "zoom", "scale", "tamano"],
      },
      {
        id: "fontFamily",
        type: "select",
        titleKey: "settings.fontFamily.label",
        descriptionKey: "settings.fontFamily.description",
        options: [
          { value: "system", labelKey: "settings.fontFamily.options.system" },
          { value: "humanist", labelKey: "settings.fontFamily.options.humanist" },
          { value: "geometric", labelKey: "settings.fontFamily.options.geometric" },
          { value: "serif", labelKey: "settings.fontFamily.options.serif" },
          { value: "mono", labelKey: "settings.fontFamily.options.mono" },
        ],
        keywords: ["font", "typeface", "typography", "fuente", "tipografia"],
      },
      {
        id: "translucencyEnabled",
        type: "toggle",
        titleKey: "settings.translucency.label",
        descriptionKey: "settings.translucency.description",
        keywords: ["glass", "blur", "transparent", "transparencia", "frosted"],
      },
      {
        id: "animationsEnabled",
        type: "toggle",
        titleKey: "settings.animations.label",
        descriptionKey: "settings.animations.description",
        keywords: ["motion", "transition", "animaciones"],
      },
      {
        id: "minimizeToTray",
        type: "toggle",
        titleKey: "settings.tray.label",
        descriptionKey: "settings.tray.description",
        keywords: ["system tray", "minimize", "bandeja", "background"],
      },
      {
        id: "rememberWindowSize",
        type: "toggle",
        titleKey: "settings.windowSize.label",
        descriptionKey: "settings.windowSize.description",
        keywords: ["resize", "window", "size", "persist", "tamano", "ventana"],
      },
    ],
  },
  {
    id: "chat",
    titleKey: "settings.sections.chat",
    keywords: [
      "chat",
      "reminder",
      "recurring",
      "context",
      "workers",
      "cores",
      "language",
      "idioma",
      "recordatorio",
      "commands",
      "blocked",
      "allowed",
      "comandos",
    ],
    items: [
      {
        id: "reminderInterval",
        type: "select",
        titleKey: "settings.reminderInterval.label",
        descriptionKey: "settings.reminderInterval.description",
        keywords: ["reminder", "interval", "memory", "context", "messages", "recordatorio"],
      },
      {
        id: "forceResponseLanguage",
        type: "toggle",
        titleKey: "settings.forceResponseLanguage.label",
        descriptionKey: "settings.forceResponseLanguage.description",
        keywords: ["language", "force", "idioma", "respuesta", "response"],
      },
      {
        id: "responseLanguage",
        type: "select",
        titleKey: "settings.responseLanguage.label",
        descriptionKey: "settings.responseLanguage.description",
        options: [
          { value: "en", labelKey: "settings.responseLanguage.options.en" },
          { value: "es", labelKey: "settings.responseLanguage.options.es" },
        ],
        keywords: ["language", "idioma", "respuesta", "response"],
      },
      {
        id: "blockedCommands",
        type: "list",
        titleKey: "settings.blockedCommands.label",
        descriptionKey: "settings.blockedCommands.description",
        keywords: [
          "commands",
          "blocked",
          "shell",
          "deny",
          "forbidden",
          "comandos",
          "bloqueados",
          "shell",
        ],
      },
      {
        id: "allowedCommands",
        type: "list",
        titleKey: "settings.allowedCommands.label",
        descriptionKey: "settings.allowedCommands.description",
        keywords: [
          "commands",
          "allowed",
          "shell",
          "auto",
          "permit",
          "comandos",
          "permitidos",
          "shell",
        ],
      },
      {
        id: "notificationsEnabled",
        type: "toggle",
        titleKey: "settings.notificationsEnabled.label",
        descriptionKey: "settings.notificationsEnabled.description",
        keywords: ["notifications", "desktop", "alerts", "notificaciones", "alertas"],
      },
      {
        id: "taskCompleteSoundEnabled",
        type: "toggle",
        titleKey: "settings.taskCompleteSoundEnabled.label",
        descriptionKey: "settings.taskCompleteSoundEnabled.description",
        keywords: ["sound", "audio", "notification", "task", "complete", "sonido"],
      },
      {
        id: "workspaceMemoryEnabled",
        type: "toggle",
        titleKey: "settings.workspaceMemoryEnabled.label",
        descriptionKey: "settings.workspaceMemoryEnabled.description",
        keywords: [
          "memory",
          "workspace",
          "notes",
          "annotations",
          "memoria",
          "anotaciones",
          "notas",
        ],
      },
      {
        id: "maxWorkerCores",
        type: "select",
        titleKey: "settings.maxWorkerCores.label",
        descriptionKey: "settings.maxWorkerCores.description",
        keywords: ["cpu", "cores", "threads", "parallel", "workers", "nucleos"],
      },
    ],
  },
  {
    id: "modelChoices",
    titleKey: "settings.sections.modelChoices",
    descriptionKey: "settings.modelChoices.description",
    keywords: [
      "model",
      "title",
      "session",
      "generation",
      "app",
      "skills",
      "agents",
      "titulo",
      "sesion",
    ],
    items: [
      {
        id: "titleGenerationModel",
        type: "modelChoice",
        titleKey: "settings.titleGenerationModel.label",
        descriptionKey: "settings.titleGenerationModel.description",
        keywords: ["model", "title", "session", "generation", "titulo", "sesion"],
      },
      {
        id: "titleUseFirstMessage",
        type: "toggle",
        titleKey: "settings.titleUseFirstMessage.label",
        descriptionKey: "settings.titleUseFirstMessage.description",
        keywords: ["first", "message", "title", "cost", "save", "primer", "mensaje", "ahorrar"],
      },
      {
        id: "appGenerationModel",
        type: "modelChoice",
        titleKey: "settings.appGenerationModel.label",
        descriptionKey: "settings.appGenerationModel.description",
        keywords: ["model", "app", "generation", "skills", "agents", "generacion", "interno"],
      },
    ],
  },
  {
    id: "lsps",
    titleKey: "settings.sections.lsps",
    keywords: ["lsp", "language", "server", "code", "navigation", "diagnostics"],
    items: [
      {
        id: "lspEnabled",
        type: "toggle",
        titleKey: "settings.lspEnabled.label",
        descriptionKey: "settings.lspEnabled.description",
        keywords: ["lsp", "language", "server", "code", "navigation", "diagnostics"],
      },
    ],
  },
  {
    id: "providers",
    titleKey: "settings.sections.providers",
    descriptionKey: "providers.description",
    keywords: [
      "provider",
      "api",
      "openai",
      "anthropic",
      "gemini",
      "model",
      "endpoint",
      "proveedor",
    ],
    items: [],
  },
  {
    id: "skills",
    titleKey: "settings.sections.skills",
    descriptionKey: "skills.description",
    keywords: ["skill", "ability", "habilidad", "context", "contexto"],
    items: [],
  },
  {
    id: "agents",
    titleKey: "settings.sections.agents",
    descriptionKey: "agents.description",
    keywords: ["agent", "agente", "persona", "tools", "herramientas"],
    items: [],
  },
  {
    id: "agentsMd",
    titleKey: "settings.sections.agentsMd",
    descriptionKey: "agentsMd.description",
    keywords: ["agents.md", "AGENTS.md", "instructions", "instrucciones"],
    items: [],
  },
  {
    id: "keybindings",
    titleKey: "settings.sections.keybindings",
    descriptionKey: "settings.keybindings.description",
    keywords: ["shortcut", "hotkey", "atajo", "keyboard"],
    items: [
      {
        id: "settings.open",
        type: "keybinding",
        titleKey: "settings.keybindings.actions.settings.open",
        descriptionKey: "settings.keybindings.description",
        keywords: ["shortcut", "hotkey", "atajo"],
      },
      {
        id: "settings.close",
        type: "keybinding",
        titleKey: "settings.keybindings.actions.settings.close",
        descriptionKey: "settings.keybindings.description",
        keywords: ["shortcut", "hotkey", "atajo"],
      },
      {
        id: "sidebar.toggle",
        type: "keybinding",
        titleKey: "settings.keybindings.actions.sidebar.toggle",
        descriptionKey: "settings.keybindings.description",
        keywords: ["shortcut", "hotkey", "sidebar"],
      },
      {
        id: "chat.clear",
        type: "keybinding",
        titleKey: "settings.keybindings.actions.chat.clear",
        descriptionKey: "settings.keybindings.description",
        keywords: ["shortcut", "hotkey", "clear", "composer"],
      },
      {
        id: "editor.save",
        type: "keybinding",
        titleKey: "settings.keybindings.actions.editor.save",
        descriptionKey: "settings.keybindings.description",
        keywords: ["shortcut", "hotkey", "save", "guardar", "ctrl"],
      },
    ],
  },
  {
    id: "debug",
    titleKey: "settings.sections.debug",
    keywords: ["devtools", "inspector", "debug", "depuracion"],
    items: [
      {
        id: "openDevtools",
        type: "action",
        titleKey: "settings.debug.devtools.label",
        descriptionKey: "settings.debug.devtools.description",
        keywords: ["devtools", "inspector", "console", "debug"],
      },
    ],
  },
];
